const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const source=fs.readFileSync(require('path').join(__dirname, '../ai.js'),'utf8');
const fakeKey='MOCK_ONLY_NOT_A_REAL_KEY';
function runtime(fetchImpl, overrides={}) { const listeners={}; const w={addEventListener:(name,cb)=>listeners[name]=cb}; const c={window:w,fetch:fetchImpl,AbortController,TextEncoder,TextDecoder,setTimeout,clearTimeout,...overrides}; vm.runInNewContext(source,c); return {api:w.HerAI,listeners}; }
const response=(lines=['一场雨。'])=>new Response(JSON.stringify({choices:[{message:{content:JSON.stringify({lines})}}]}),{status:200,headers:{'Content-Type':'application/json'}});
const input={scene:{id:'first_rain',prompt:['雨是什么？']},input:'你好',rainName:'小雨',recent:[]};
(async()=>{
 let checks=0;
 const check=async(name,fn)=>{await fn(); checks++; console.log('PASS '+name)};
 await check('fixed endpoint, model, header, omitted credentials, no redirect or referrer',async()=>{let call;let{api}=runtime(async(...args)=>(call=args,response()));assert(api.connect(fakeKey)); await api.request(input);assert.equal(call[0],'https://www.dmxapi.cn/v1/chat/completions');assert.equal(call[1].headers.Authorization,`Bearer ${fakeKey}`);assert.equal(JSON.parse(call[1].body).model,'glm-5.3-flash');assert(!call[1].body.includes(fakeKey));assert.equal(call[1].credentials,'omit');assert.equal(call[1].redirect,'error');assert.equal(call[1].referrerPolicy,'no-referrer')});
 await check('invalid credentials rejected without outbound call',async()=>{let calls=0;let{api}=runtime(async()=>{calls++;return response()});for(const key of ['', 'short',fakeKey+'\r\nBAD', 'x'.repeat(501)])assert.equal(api.connect(key),false);await assert.rejects(api.request(input),e=>e.code==='disconnected');assert.equal(calls,0)});
 await check('disconnected and pagehide clear volatile key',async()=>{let calls=0;let{api,listeners}=runtime(async()=>{calls++;return response()});api.connect(fakeKey);listeners.pagehide();assert.equal(api.connected(),false);await assert.rejects(api.request(input),e=>e.code==='disconnected');assert.equal(calls,0)});
 await check('upstream echo of exact key rejected',async()=>{let{api}=runtime(async()=>response([fakeKey]));api.connect(fakeKey);await assert.rejects(api.request(input),e=>e.code==='format'&&!e.message.includes(fakeKey))});
 await check('authentication, quota, upstream errors do not expose response bodies',async()=>{for(const[status,code]of[[401,'auth'],[403,'auth'],[429,'quota'],[500,'upstream']]){let{api}=runtime(async()=>new Response(fakeKey,{status}));api.connect(fakeKey);await assert.rejects(api.request(input),e=>e.code===code&&!e.message.includes(fakeKey))}});
 await check('network exception sanitized',async()=>{let{api}=runtime(async()=>{throw new Error(fakeKey)});api.connect(fakeKey);await assert.rejects(api.request(input),e=>e.code==='network'&&!e.message.includes(fakeKey))});
 await check('ordinary prose, content text arrays and fenced JSON are accepted',async()=>{for(const content of ['雨落下来了。\\n我想再看一会儿。',[{type:'text',text:'你说的，我听见了。'}],'```json\\n{"lines":["我们慢慢来。"],"scene":999}\\n```']){const normalized=typeof content==='string'?content.replaceAll('\\n','\n'):content;let{api}=runtime(async()=>new Response(JSON.stringify({choices:[{message:{content:normalized}}]})));api.connect(fakeKey);const lines=await api.request(input);assert(lines.length>0);assert(!lines.join('').includes('scene'));}});
 await check('malformed JSON-looking and unsupported structured content rejected',async()=>{for(const content of ['{"lines":',JSON.stringify({reasoning_content:'private'}),JSON.stringify({lines:[]}),JSON.stringify({lines:[1]})]){let{api}=runtime(async()=>new Response(JSON.stringify({choices:[{message:{content}}]})));api.connect(fakeKey);await assert.rejects(api.request(input),e=>e.code==='format')}});
 await check('reasoning-only and truncation never expose reasoning',async()=>{for(const [content,finish_reason,code] of [[null,'length','truncated'],['','stop','empty'],['<think>private','length','truncated']]){let{api}=runtime(async()=>new Response(JSON.stringify({choices:[{message:{content,reasoning_content:'private'},finish_reason}]})));api.connect(fakeKey);await assert.rejects(api.request(input),e=>e.code===code&&!e.message.includes('private'));}});
 await check('final text is bounded and marked analysis is hidden',async()=>{let{api}=runtime(async()=>new Response(JSON.stringify({choices:[{message:{content:'<think>private</think>雨'.repeat(600)}}]})));api.connect(fakeKey);const lines=await api.request(input);assert(lines.join('').length<=450);assert(!lines.join('').includes('private'));});
 await check('response over byte cap rejected',async()=>{let{api}=runtime(async()=>new Response('a'.repeat(65537)));api.connect(fakeKey);await assert.rejects(api.request(input),e=>e.code==='format')});
 await check('only one concurrent request, disconnect aborts request',async()=>{let calls=0;let{api}=runtime((url,o)=>{calls++;return new Promise((res,rej)=>o.signal.addEventListener('abort',()=>rej(new DOMException('aborted','AbortError'))))});api.connect(fakeKey);const pending=api.request(input);await assert.rejects(api.request(input),e=>e.code==='busy');api.disconnect();await assert.rejects(pending,e=>e.code==='cancelled');assert.equal(calls,1);assert.equal(api.connected(),false)});
 await check('20-call page session reminder cap',async()=>{let calls=0;let{api}=runtime(async()=>{calls++;return response()});api.connect(fakeKey);for(let i=0;i<20;i++)await api.request(input);await assert.rejects(api.request(input),e=>e.code==='limit');assert.equal(calls,20)});
 await check('timeout aborts and does not retry',async()=>{let timer,calls=0;let{api}=runtime((url,o)=>{calls++;return new Promise((res,rej)=>o.signal.addEventListener('abort',()=>rej(new DOMException('aborted','AbortError'))))},{setTimeout:fn=>(timer=fn,1),clearTimeout:()=>{}});api.connect(fakeKey);const pending=api.request(input);timer();await assert.rejects(pending,e=>e.code==='timeout');assert.equal(calls,1)});
 console.log(`${checks} mock-only transport checks passed; no network used.`)
})().catch(e=>{console.error(e);process.exit(1)});
